version: '2'

services:
  collectd:
    build: collectd
    volumes:
      - ./collectd/collectd.conf:/etc/collectd/collectd.conf
    networks:
      - code-network
  influxdb:
    image: influxdb:1.3.5
    ports:
      - "8083:8083"
      - "8086:8086"
#      - "25826:25826/udp"
    volumes:
      - ./influxDB/data:/var/lib/influxdb
      - ./influxDB/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxDB/types.db:/usr/share/collectd/types.db:ro
    networks:
      - code-network
  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - code-network
  pinba:
    image: pinba_users:latest
    volumes:
      - ./pinba/my.conf:/local/mysql/etc/my.cnf
    ports:
      - "3306:3306"
      - "30002:30002/udp"
    networks:
      - code-network

networks:
    code-network:
        driver: bridge

